apiVersion: batch/v1
kind: CronJob
metadata:
  name: scanner
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: scanner
            image: pejkokonik/scanner:dev
            imagePullPolicy: IfNotPresent
            command: ["/bin/sh"]
            args: ["-c", "python scanner.py 192.168.1.0/24 --s 1 --e 500"]
          restartPolicy: OnFailure